import{a as b,S as w,i as d}from"./assets/vendor-Db2TdIkw.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const P="49635382-66eda9712402d4470ed35045b",E="https://pixabay.com/api/",M=15;async function $(r,e=1){try{const{data:s}=await b.get(E,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:M}});return{images:s.hits,total:s.totalHits}}catch(s){return console.error("Error fetching images:",s.message),{images:[],total:0}}}const u=document.querySelector(".gallery");let n=null;const y=document.querySelector(".end-message");document.querySelector(".load-more");function x(r,e){const s=r.map(({webformatURL:l,largeImageURL:t,tags:o,likes:a,views:S,comments:q,downloads:v})=>`<a href="${t}" class="gallery-item">
        <img src="${l}" alt="${o}" />
        <div class="info">
          <p>👍 ${a}</p>
          <p>👀 ${S}</p>
          <p>💬 ${q}</p>
          <p>⬇️ ${v}</p>
        </div>
      </a>`).join("");e?u.innerHTML=s:u.insertAdjacentHTML("beforeend",s),n?n.refresh():n=new w(".gallery a",{captionsData:"alt",captionDelay:250})}function C(){u.innerHTML="",n&&(n.destroy(),n=null)}function h(){document.querySelector(".loader").classList.add("visible")}function g(){document.querySelector(".loader").classList.remove("visible")}function H(){y.classList.remove("hidden"),y.textContent="We're sorry, but you've reached the end of search results."}const f=document.querySelector(".form"),O=f.querySelector("input[name='search-text']"),i=document.querySelector(".load-more"),A=document.querySelector(".end-message");let c=1,p="",m=0;f.addEventListener("submit",async r=>{r.preventDefault();const e=O.value.trim();if(!e){d.error({message:"Please enter a search query!"});return}B(e),await L(!1)});i.addEventListener("click",async()=>{c++,await L(!0)});function B(r){C(),h(),i.classList.add("hidden"),A.classList.add("hidden"),p=r,c=1,m=0}async function L(r){h();try{const{images:e,total:s}=await $(p,c);if(g(),m=s,!e.length){d.info({message:"Sorry, there are no images matching your search query. Please try again!"}),i.classList.add("hidden");return}x(e,c===1),m<=c*15?(i.classList.add("hidden"),H()):i.classList.remove("hidden"),r&&T()}catch(e){g(),d.error({message:"Something went wrong while loading images."}),console.error(e)}finally{f.reset()}}function T(){const r=document.querySelector(".gallery .gallery-item");if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*3,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
